# Generated by Django 4.2.16 on 2025-04-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
