# Generated by Django 4.2.16 on 2025-04-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
