# Generated by Django 4.2.16 on 2025-04-09 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_tasksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('solution_file', models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/%d/', verbose_name='Файл с решением')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('no_answer', 'Ответ не прикреплен'), ('under_review', 'На проверке'), ('graded', 'Оценено')], default='no_answer', max_length=20, verbose_name='Статус')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('teacher_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student', verbose_name='Студент')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
                'ordering': ['-submitted_at'],
                'unique_together': {('task', 'student')},
            },
        ),
    ]
