# Generated by Django 4.2.16 on 2025-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_role_user_student_user_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (открытый)'),
        ),
    ]
